### PR TITLE
Add caskdb to pypi 

### PR DESCRIPTION
**Pull request by avinassh**
Status:

- Locally now it can be installed via `python setup.py install` and then importing `from cdbpie import DiskStorage`
- WIP: If I pip install the same, it breaks saying module `cdbpie` cannot found

### CODE REVIEW

**Comment by widp** [comment]
This works for me locally (`pip install .`).
Could it be an issue with the URL and pypi 
`url="https://github.com/avinassh/cdb/",`

**Comment by avinassh** [comment]
Hey @widp thank you for checking. URL doesn't make any difference though. 

I think `pip install .` is same as `python setup.py install`

I want to upload this lib to PyPi, so people can just do `pip install caskdb`

**Comment by avinassh** [comment]
exlporing `pyproject.toml` might be a good idea - https://til.simonwillison.net/python/pyproject

**Comment by tusharsadhwani** [comment]
I can help with this, I have [a few packages](https://pypi.org/user/tusharsadhwani) on PyPI. Should I give it a shot?

**Comment by avinassh** [comment]
@tusharsadhwani yes, go ahead!

**Pull request closed without merging**
